### ISSUE TITLE
old npm version

### ISSUE THREAD

**Issue by sylhero** [shirohana/native-require#2]
Hi,

I just tried `npm install native-require` but I'm still getting the 1.0.0, which is the older version. Did u also publish the latest version to npm?

**Comment by shirohana** [comment]
You didn't `--save` or `--save-dev` so your `package.json` would not been updated.

By the way, you can just reply on exists Issue https://github.com/shirohana/native-require/issues/1 because this is a associated problem.

**Comment by shirohana** [comment]
I close the issue just mark it as a 'solved problem', you can still communicate on it.
